services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - calldisbknd
    volumes:
      - ${PROJECT_ROOT}/:/usr/local/apache2/htdocs/
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    networks:
      - calldisnet
      - calldisbknd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROJECT_ROOT}/:/usr/local/apache2/htdocs/
    container_name: apache
networks:
  calldisnet:
  calldisbknd:
volumes:
    data:
